namespace WindowsFormsApp1.Forms
{
	partial class Teacher
	{
		/// <summary>
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose(bool disposing)
		{
			if (disposing && (components != null))
			{
				components.Dispose();
			}
			base.Dispose(disposing);
		}

		#region Windows Form Designer generated code

		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
			this.components = new System.ComponentModel.Container();
			System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Teacher));
			System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
			System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
			System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
			Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
			Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
			Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
			Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
			Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
			Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
			Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
			Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
			this.bunifuBarChart1 = new Bunifu.Charts.WinForms.ChartTypes.BunifuBarChart(this.components);
			this.TeacherRecordsTable = new Bunifu.UI.WinForms.BunifuDataGridView();
			this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
			this.Add_Teacher = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
			this.EditApplier_Button = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
			this.GoBack_Button = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
			this.HireDate_Label = new Bunifu.UI.WinForms.BunifuLabel();
			this.Phone_Label = new Bunifu.UI.WinForms.BunifuLabel();
			this.SubjectID_Label = new Bunifu.UI.WinForms.BunifuLabel();
			this.Name_Label = new Bunifu.UI.WinForms.BunifuLabel();
			this.SubjectID_comboBox = new System.Windows.Forms.ComboBox();
			this.HireDate_DatePicker = new Bunifu.UI.WinForms.BunifuDatePicker();
			this.Phone_TextBox = new Bunifu.UI.WinForms.BunifuTextBox();
			this.FullName_TextBox = new Bunifu.UI.WinForms.BunifuTextBox();
			this.Back_Button_2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
			this.Insert_Button = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
			this.Assign_Button = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
			this.Assign_Class_Button = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
			this.Delet_Button = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
			this.Edit_Button = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
			this.message = new Bunifu.UI.WinForms.BunifuSnackbar(this.components);
			((System.ComponentModel.ISupportInitialize)(this.TeacherRecordsTable)).BeginInit();
			this.bunifuPanel1.SuspendLayout();
			this.SuspendLayout();
			// 
			// bunifuBarChart1
			// 
			this.bunifuBarChart1.BackgroundColor = ((System.Collections.Generic.List<System.Drawing.Color>)(resources.GetObject("bunifuBarChart1.BackgroundColor")));
			this.bunifuBarChart1.BorderColor = ((System.Collections.Generic.List<System.Drawing.Color>)(resources.GetObject("bunifuBarChart1.BorderColor")));
			this.bunifuBarChart1.BorderSkipped = null;
			this.bunifuBarChart1.BorderWidth = 0;
			this.bunifuBarChart1.Data = ((System.Collections.Generic.List<double>)(resources.GetObject("bunifuBarChart1.Data")));
			this.bunifuBarChart1.HoverBackgroundColor = System.Drawing.Color.Empty;
			this.bunifuBarChart1.HoverBorderColor = System.Drawing.Color.Empty;
			this.bunifuBarChart1.HoverBorderWidth = 0;
			this.bunifuBarChart1.Label = "Label here";
			this.bunifuBarChart1.TargetCanvas = null;
			// 
			// TeacherRecordsTable
			// 
			this.TeacherRecordsTable.AllowCustomTheming = false;
			dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(203)))), ((int)(((byte)(211)))), ((int)(((byte)(211)))));
			dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
			this.TeacherRecordsTable.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
			this.TeacherRecordsTable.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
			this.TeacherRecordsTable.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this.TeacherRecordsTable.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
			this.TeacherRecordsTable.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
			dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle2.BackColor = System.Drawing.Color.DarkSlateGray;
			dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
			dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
			dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(37)))), ((int)(((byte)(63)))), ((int)(((byte)(63)))));
			dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
			dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
			this.TeacherRecordsTable.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
			this.TeacherRecordsTable.ColumnHeadersHeight = 40;
			this.TeacherRecordsTable.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(203)))), ((int)(((byte)(211)))), ((int)(((byte)(211)))));
			this.TeacherRecordsTable.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
			this.TeacherRecordsTable.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
			this.TeacherRecordsTable.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(130)))), ((int)(((byte)(149)))), ((int)(((byte)(149)))));
			this.TeacherRecordsTable.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.White;
			this.TeacherRecordsTable.CurrentTheme.BackColor = System.Drawing.Color.DarkSlateGray;
			this.TeacherRecordsTable.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(202)))), ((int)(((byte)(202)))));
			this.TeacherRecordsTable.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DarkSlateGray;
			this.TeacherRecordsTable.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
			this.TeacherRecordsTable.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
			this.TeacherRecordsTable.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(37)))), ((int)(((byte)(63)))), ((int)(((byte)(63)))));
			this.TeacherRecordsTable.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
			this.TeacherRecordsTable.CurrentTheme.Name = null;
			this.TeacherRecordsTable.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(219)))), ((int)(((byte)(219)))));
			this.TeacherRecordsTable.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
			this.TeacherRecordsTable.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
			this.TeacherRecordsTable.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(130)))), ((int)(((byte)(149)))), ((int)(((byte)(149)))));
			this.TeacherRecordsTable.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.White;
			dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle3.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(219)))), ((int)(((byte)(219)))));
			dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
			dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
			dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(130)))), ((int)(((byte)(149)))), ((int)(((byte)(149)))));
			dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.White;
			dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
			this.TeacherRecordsTable.DefaultCellStyle = dataGridViewCellStyle3;
			this.TeacherRecordsTable.EnableHeadersVisualStyles = false;
			this.TeacherRecordsTable.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(202)))), ((int)(((byte)(202)))));
			this.TeacherRecordsTable.HeaderBackColor = System.Drawing.Color.DarkSlateGray;
			this.TeacherRecordsTable.HeaderBgColor = System.Drawing.Color.Empty;
			this.TeacherRecordsTable.HeaderForeColor = System.Drawing.Color.White;
			this.TeacherRecordsTable.Location = new System.Drawing.Point(65, 157);
			this.TeacherRecordsTable.Name = "TeacherRecordsTable";
			this.TeacherRecordsTable.RowHeadersVisible = false;
			this.TeacherRecordsTable.RowHeadersWidth = 82;
			this.TeacherRecordsTable.RowTemplate.Height = 40;
			this.TeacherRecordsTable.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
			this.TeacherRecordsTable.Size = new System.Drawing.Size(905, 331);
			this.TeacherRecordsTable.TabIndex = 8;
			this.TeacherRecordsTable.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.DarkSlateGray;
			this.TeacherRecordsTable.CellContentClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.TeacherRecordsTable_CellContentClick);
			// 
			// bunifuPanel1
			// 
			this.bunifuPanel1.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(76)))));
			this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
			this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
			this.bunifuPanel1.BorderColor = System.Drawing.Color.White;
			this.bunifuPanel1.BorderRadius = 8;
			this.bunifuPanel1.BorderThickness = 1;
			this.bunifuPanel1.Controls.Add(this.Add_Teacher);
			this.bunifuPanel1.Controls.Add(this.EditApplier_Button);
			this.bunifuPanel1.Controls.Add(this.GoBack_Button);
			this.bunifuPanel1.Controls.Add(this.HireDate_Label);
			this.bunifuPanel1.Controls.Add(this.Phone_Label);
			this.bunifuPanel1.Controls.Add(this.SubjectID_Label);
			this.bunifuPanel1.Controls.Add(this.Name_Label);
			this.bunifuPanel1.Controls.Add(this.SubjectID_comboBox);
			this.bunifuPanel1.Controls.Add(this.HireDate_DatePicker);
			this.bunifuPanel1.Controls.Add(this.Phone_TextBox);
			this.bunifuPanel1.Controls.Add(this.FullName_TextBox);
			this.bunifuPanel1.Location = new System.Drawing.Point(304, 91);
			this.bunifuPanel1.Name = "bunifuPanel1";
			this.bunifuPanel1.ShowBorders = true;
			this.bunifuPanel1.Size = new System.Drawing.Size(991, 622);
			this.bunifuPanel1.TabIndex = 10;
			this.bunifuPanel1.Click += new System.EventHandler(this.bunifuPanel1_Click);
			// 
			// Add_Teacher
			// 
			this.Add_Teacher.AllowAnimations = true;
			this.Add_Teacher.AllowMouseEffects = true;
			this.Add_Teacher.AllowToggling = false;
			this.Add_Teacher.AnimationSpeed = 200;
			this.Add_Teacher.AutoGenerateColors = false;
			this.Add_Teacher.AutoRoundBorders = false;
			this.Add_Teacher.AutoSizeLeftIcon = true;
			this.Add_Teacher.AutoSizeRightIcon = true;
			this.Add_Teacher.BackColor = System.Drawing.Color.Transparent;
			this.Add_Teacher.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
			this.Add_Teacher.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Add_Teacher.BackgroundImage")));
			this.Add_Teacher.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.Add_Teacher.ButtonText = "Insert";
			this.Add_Teacher.ButtonTextMarginLeft = 0;
			this.Add_Teacher.ColorContrastOnClick = 45;
			this.Add_Teacher.ColorContrastOnHover = 45;
			this.Add_Teacher.Cursor = System.Windows.Forms.Cursors.Default;
			borderEdges1.BottomLeft = true;
			borderEdges1.BottomRight = true;
			borderEdges1.TopLeft = true;
			borderEdges1.TopRight = true;
			this.Add_Teacher.CustomizableEdges = borderEdges1;
			this.Add_Teacher.DialogResult = System.Windows.Forms.DialogResult.None;
			this.Add_Teacher.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
			this.Add_Teacher.DisabledFillColor = System.Drawing.Color.Empty;
			this.Add_Teacher.DisabledForecolor = System.Drawing.Color.Empty;
			this.Add_Teacher.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
			this.Add_Teacher.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.Add_Teacher.ForeColor = System.Drawing.Color.White;
			this.Add_Teacher.IconLeft = null;
			this.Add_Teacher.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.Add_Teacher.IconLeftCursor = System.Windows.Forms.Cursors.Default;
			this.Add_Teacher.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
			this.Add_Teacher.IconMarginLeft = 11;
			this.Add_Teacher.IconPadding = 10;
			this.Add_Teacher.IconRight = null;
			this.Add_Teacher.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
			this.Add_Teacher.IconRightCursor = System.Windows.Forms.Cursors.Default;
			this.Add_Teacher.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
			this.Add_Teacher.IconSize = 25;
			this.Add_Teacher.IdleBorderColor = System.Drawing.Color.Empty;
			this.Add_Teacher.IdleBorderRadius = 0;
			this.Add_Teacher.IdleBorderThickness = 0;
			this.Add_Teacher.IdleFillColor = System.Drawing.Color.Empty;
			this.Add_Teacher.IdleIconLeftImage = null;
			this.Add_Teacher.IdleIconRightImage = null;
			this.Add_Teacher.IndicateFocus = false;
			this.Add_Teacher.Location = new System.Drawing.Point(753, 427);
			this.Add_Teacher.Margin = new System.Windows.Forms.Padding(6);
			this.Add_Teacher.Name = "Add_Teacher";
			this.Add_Teacher.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
			this.Add_Teacher.OnDisabledState.BorderRadius = 1;
			this.Add_Teacher.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.Add_Teacher.OnDisabledState.BorderThickness = 1;
			this.Add_Teacher.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.Add_Teacher.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
			this.Add_Teacher.OnDisabledState.IconLeftImage = null;
			this.Add_Teacher.OnDisabledState.IconRightImage = null;
			this.Add_Teacher.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
			this.Add_Teacher.onHoverState.BorderRadius = 1;
			this.Add_Teacher.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.Add_Teacher.onHoverState.BorderThickness = 1;
			this.Add_Teacher.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
			this.Add_Teacher.onHoverState.ForeColor = System.Drawing.Color.White;
			this.Add_Teacher.onHoverState.IconLeftImage = null;
			this.Add_Teacher.onHoverState.IconRightImage = null;
			this.Add_Teacher.OnIdleState.BorderColor = System.Drawing.Color.Silver;
			this.Add_Teacher.OnIdleState.BorderRadius = 1;
			this.Add_Teacher.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.Add_Teacher.OnIdleState.BorderThickness = 1;
			this.Add_Teacher.OnIdleState.FillColor = System.Drawing.Color.DimGray;
			this.Add_Teacher.OnIdleState.ForeColor = System.Drawing.Color.White;
			this.Add_Teacher.OnIdleState.IconLeftImage = null;
			this.Add_Teacher.OnIdleState.IconRightImage = null;
			this.Add_Teacher.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(71)))));
			this.Add_Teacher.OnPressedState.BorderRadius = 1;
			this.Add_Teacher.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.Add_Teacher.OnPressedState.BorderThickness = 1;
			this.Add_Teacher.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(71)))));
			this.Add_Teacher.OnPressedState.ForeColor = System.Drawing.Color.White;
			this.Add_Teacher.OnPressedState.IconLeftImage = null;
			this.Add_Teacher.OnPressedState.IconRightImage = null;
			this.Add_Teacher.Size = new System.Drawing.Size(196, 62);
			this.Add_Teacher.TabIndex = 27;
			this.Add_Teacher.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			this.Add_Teacher.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
			this.Add_Teacher.TextMarginLeft = 0;
			this.Add_Teacher.TextPadding = new System.Windows.Forms.Padding(0);
			this.Add_Teacher.UseDefaultRadiusAndThickness = true;
			this.Add_Teacher.Click += new System.EventHandler(this.bunifuButton2_Click);
			// 
			// EditApplier_Button
			// 
			this.EditApplier_Button.AllowAnimations = true;
			this.EditApplier_Button.AllowMouseEffects = true;
			this.EditApplier_Button.AllowToggling = false;
			this.EditApplier_Button.AnimationSpeed = 200;
			this.EditApplier_Button.AutoGenerateColors = false;
			this.EditApplier_Button.AutoRoundBorders = false;
			this.EditApplier_Button.AutoSizeLeftIcon = true;
			this.EditApplier_Button.AutoSizeRightIcon = true;
			this.EditApplier_Button.BackColor = System.Drawing.Color.Transparent;
			this.EditApplier_Button.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
			this.EditApplier_Button.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("EditApplier_Button.BackgroundImage")));
			this.EditApplier_Button.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.EditApplier_Button.ButtonText = "Change";
			this.EditApplier_Button.ButtonTextMarginLeft = 0;
			this.EditApplier_Button.ColorContrastOnClick = 45;
			this.EditApplier_Button.ColorContrastOnHover = 45;
			this.EditApplier_Button.Cursor = System.Windows.Forms.Cursors.Default;
			borderEdges2.BottomLeft = true;
			borderEdges2.BottomRight = true;
			borderEdges2.TopLeft = true;
			borderEdges2.TopRight = true;
			this.EditApplier_Button.CustomizableEdges = borderEdges2;
			this.EditApplier_Button.DialogResult = System.Windows.Forms.DialogResult.None;
			this.EditApplier_Button.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
			this.EditApplier_Button.DisabledFillColor = System.Drawing.Color.Empty;
			this.EditApplier_Button.DisabledForecolor = System.Drawing.Color.Empty;
			this.EditApplier_Button.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
			this.EditApplier_Button.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.EditApplier_Button.ForeColor = System.Drawing.Color.White;
			this.EditApplier_Button.IconLeft = null;
			this.EditApplier_Button.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.EditApplier_Button.IconLeftCursor = System.Windows.Forms.Cursors.Default;
			this.EditApplier_Button.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
			this.EditApplier_Button.IconMarginLeft = 11;
			this.EditApplier_Button.IconPadding = 10;
			this.EditApplier_Button.IconRight = null;
			this.EditApplier_Button.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
			this.EditApplier_Button.IconRightCursor = System.Windows.Forms.Cursors.Default;
			this.EditApplier_Button.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
			this.EditApplier_Button.IconSize = 25;
			this.EditApplier_Button.IdleBorderColor = System.Drawing.Color.Empty;
			this.EditApplier_Button.IdleBorderRadius = 0;
			this.EditApplier_Button.IdleBorderThickness = 0;
			this.EditApplier_Button.IdleFillColor = System.Drawing.Color.Empty;
			this.EditApplier_Button.IdleIconLeftImage = null;
			this.EditApplier_Button.IdleIconRightImage = null;
			this.EditApplier_Button.IndicateFocus = false;
			this.EditApplier_Button.Location = new System.Drawing.Point(532, 427);
			this.EditApplier_Button.Margin = new System.Windows.Forms.Padding(6);
			this.EditApplier_Button.Name = "EditApplier_Button";
			this.EditApplier_Button.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
			this.EditApplier_Button.OnDisabledState.BorderRadius = 1;
			this.EditApplier_Button.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.EditApplier_Button.OnDisabledState.BorderThickness = 1;
			this.EditApplier_Button.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.EditApplier_Button.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
			this.EditApplier_Button.OnDisabledState.IconLeftImage = null;
			this.EditApplier_Button.OnDisabledState.IconRightImage = null;
			this.EditApplier_Button.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
			this.EditApplier_Button.onHoverState.BorderRadius = 1;
			this.EditApplier_Button.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.EditApplier_Button.onHoverState.BorderThickness = 1;
			this.EditApplier_Button.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
			this.EditApplier_Button.onHoverState.ForeColor = System.Drawing.Color.White;
			this.EditApplier_Button.onHoverState.IconLeftImage = null;
			this.EditApplier_Button.onHoverState.IconRightImage = null;
			this.EditApplier_Button.OnIdleState.BorderColor = System.Drawing.Color.Silver;
			this.EditApplier_Button.OnIdleState.BorderRadius = 1;
			this.EditApplier_Button.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.EditApplier_Button.OnIdleState.BorderThickness = 1;
			this.EditApplier_Button.OnIdleState.FillColor = System.Drawing.Color.DimGray;
			this.EditApplier_Button.OnIdleState.ForeColor = System.Drawing.Color.White;
			this.EditApplier_Button.OnIdleState.IconLeftImage = null;
			this.EditApplier_Button.OnIdleState.IconRightImage = null;
			this.EditApplier_Button.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(71)))));
			this.EditApplier_Button.OnPressedState.BorderRadius = 1;
			this.EditApplier_Button.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.EditApplier_Button.OnPressedState.BorderThickness = 1;
			this.EditApplier_Button.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(71)))));
			this.EditApplier_Button.OnPressedState.ForeColor = System.Drawing.Color.White;
			this.EditApplier_Button.OnPressedState.IconLeftImage = null;
			this.EditApplier_Button.OnPressedState.IconRightImage = null;
			this.EditApplier_Button.Size = new System.Drawing.Size(196, 62);
			this.EditApplier_Button.TabIndex = 26;
			this.EditApplier_Button.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			this.EditApplier_Button.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
			this.EditApplier_Button.TextMarginLeft = 0;
			this.EditApplier_Button.TextPadding = new System.Windows.Forms.Padding(0);
			this.EditApplier_Button.UseDefaultRadiusAndThickness = true;
			this.EditApplier_Button.Click += new System.EventHandler(this.bunifuButton1_Click_6);
			// 
			// GoBack_Button
			// 
			this.GoBack_Button.AllowAnimations = true;
			this.GoBack_Button.AllowMouseEffects = true;
			this.GoBack_Button.AllowToggling = false;
			this.GoBack_Button.AnimationSpeed = 200;
			this.GoBack_Button.AutoGenerateColors = false;
			this.GoBack_Button.AutoRoundBorders = false;
			this.GoBack_Button.AutoSizeLeftIcon = true;
			this.GoBack_Button.AutoSizeRightIcon = true;
			this.GoBack_Button.BackColor = System.Drawing.Color.Transparent;
			this.GoBack_Button.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
			this.GoBack_Button.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("GoBack_Button.BackgroundImage")));
			this.GoBack_Button.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.GoBack_Button.ButtonText = "Back";
			this.GoBack_Button.ButtonTextMarginLeft = 0;
			this.GoBack_Button.ColorContrastOnClick = 45;
			this.GoBack_Button.ColorContrastOnHover = 45;
			this.GoBack_Button.Cursor = System.Windows.Forms.Cursors.Default;
			borderEdges3.BottomLeft = true;
			borderEdges3.BottomRight = true;
			borderEdges3.TopLeft = true;
			borderEdges3.TopRight = true;
			this.GoBack_Button.CustomizableEdges = borderEdges3;
			this.GoBack_Button.DialogResult = System.Windows.Forms.DialogResult.None;
			this.GoBack_Button.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
			this.GoBack_Button.DisabledFillColor = System.Drawing.Color.Empty;
			this.GoBack_Button.DisabledForecolor = System.Drawing.Color.Empty;
			this.GoBack_Button.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
			this.GoBack_Button.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.GoBack_Button.ForeColor = System.Drawing.Color.White;
			this.GoBack_Button.IconLeft = null;
			this.GoBack_Button.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.GoBack_Button.IconLeftCursor = System.Windows.Forms.Cursors.Default;
			this.GoBack_Button.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
			this.GoBack_Button.IconMarginLeft = 11;
			this.GoBack_Button.IconPadding = 10;
			this.GoBack_Button.IconRight = null;
			this.GoBack_Button.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
			this.GoBack_Button.IconRightCursor = System.Windows.Forms.Cursors.Default;
			this.GoBack_Button.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
			this.GoBack_Button.IconSize = 25;
			this.GoBack_Button.IdleBorderColor = System.Drawing.Color.Empty;
			this.GoBack_Button.IdleBorderRadius = 0;
			this.GoBack_Button.IdleBorderThickness = 0;
			this.GoBack_Button.IdleFillColor = System.Drawing.Color.Empty;
			this.GoBack_Button.IdleIconLeftImage = null;
			this.GoBack_Button.IdleIconRightImage = null;
			this.GoBack_Button.IndicateFocus = false;
			this.GoBack_Button.Location = new System.Drawing.Point(75, 427);
			this.GoBack_Button.Margin = new System.Windows.Forms.Padding(6);
			this.GoBack_Button.Name = "GoBack_Button";
			this.GoBack_Button.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
			this.GoBack_Button.OnDisabledState.BorderRadius = 1;
			this.GoBack_Button.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.GoBack_Button.OnDisabledState.BorderThickness = 1;
			this.GoBack_Button.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.GoBack_Button.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
			this.GoBack_Button.OnDisabledState.IconLeftImage = null;
			this.GoBack_Button.OnDisabledState.IconRightImage = null;
			this.GoBack_Button.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
			this.GoBack_Button.onHoverState.BorderRadius = 1;
			this.GoBack_Button.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.GoBack_Button.onHoverState.BorderThickness = 1;
			this.GoBack_Button.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
			this.GoBack_Button.onHoverState.ForeColor = System.Drawing.Color.White;
			this.GoBack_Button.onHoverState.IconLeftImage = null;
			this.GoBack_Button.onHoverState.IconRightImage = null;
			this.GoBack_Button.OnIdleState.BorderColor = System.Drawing.Color.Silver;
			this.GoBack_Button.OnIdleState.BorderRadius = 1;
			this.GoBack_Button.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.GoBack_Button.OnIdleState.BorderThickness = 1;
			this.GoBack_Button.OnIdleState.FillColor = System.Drawing.Color.DimGray;
			this.GoBack_Button.OnIdleState.ForeColor = System.Drawing.Color.White;
			this.GoBack_Button.OnIdleState.IconLeftImage = null;
			this.GoBack_Button.OnIdleState.IconRightImage = null;
			this.GoBack_Button.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(71)))));
			this.GoBack_Button.OnPressedState.BorderRadius = 1;
			this.GoBack_Button.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.GoBack_Button.OnPressedState.BorderThickness = 1;
			this.GoBack_Button.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(71)))));
			this.GoBack_Button.OnPressedState.ForeColor = System.Drawing.Color.White;
			this.GoBack_Button.OnPressedState.IconLeftImage = null;
			this.GoBack_Button.OnPressedState.IconRightImage = null;
			this.GoBack_Button.Size = new System.Drawing.Size(196, 62);
			this.GoBack_Button.TabIndex = 23;
			this.GoBack_Button.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			this.GoBack_Button.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
			this.GoBack_Button.TextMarginLeft = 0;
			this.GoBack_Button.TextPadding = new System.Windows.Forms.Padding(0);
			this.GoBack_Button.UseDefaultRadiusAndThickness = true;
			this.GoBack_Button.Click += new System.EventHandler(this.bunifuButton1_Click_5);
			// 
			// HireDate_Label
			// 
			this.HireDate_Label.AllowParentOverrides = false;
			this.HireDate_Label.AutoEllipsis = false;
			this.HireDate_Label.CursorType = null;
			this.HireDate_Label.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F);
			this.HireDate_Label.ForeColor = System.Drawing.SystemColors.ButtonFace;
			this.HireDate_Label.Location = new System.Drawing.Point(582, 207);
			this.HireDate_Label.Name = "HireDate_Label";
			this.HireDate_Label.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.HireDate_Label.Size = new System.Drawing.Size(134, 37);
			this.HireDate_Label.TabIndex = 25;
			this.HireDate_Label.Text = "Hire Date";
			this.HireDate_Label.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
			this.HireDate_Label.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
			this.HireDate_Label.TextRenderingHint = System.Drawing.Text.TextRenderingHint.SingleBitPerPixelGridFit;
			// 
			// Phone_Label
			// 
			this.Phone_Label.AllowParentOverrides = false;
			this.Phone_Label.AutoEllipsis = false;
			this.Phone_Label.CursorType = null;
			this.Phone_Label.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F);
			this.Phone_Label.ForeColor = System.Drawing.SystemColors.ButtonFace;
			this.Phone_Label.Location = new System.Drawing.Point(75, 207);
			this.Phone_Label.Name = "Phone_Label";
			this.Phone_Label.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Phone_Label.Size = new System.Drawing.Size(146, 37);
			this.Phone_Label.TabIndex = 24;
			this.Phone_Label.Text = "Phone no.";
			this.Phone_Label.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
			this.Phone_Label.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
			// 
			// SubjectID_Label
			// 
			this.SubjectID_Label.AllowParentOverrides = false;
			this.SubjectID_Label.AutoEllipsis = false;
			this.SubjectID_Label.CursorType = null;
			this.SubjectID_Label.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F);
			this.SubjectID_Label.ForeColor = System.Drawing.SystemColors.ButtonFace;
			this.SubjectID_Label.Location = new System.Drawing.Point(582, 51);
			this.SubjectID_Label.Name = "SubjectID_Label";
			this.SubjectID_Label.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.SubjectID_Label.Size = new System.Drawing.Size(106, 37);
			this.SubjectID_Label.TabIndex = 23;
			this.SubjectID_Label.Text = "Subject";
			this.SubjectID_Label.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
			this.SubjectID_Label.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
			// 
			// Name_Label
			// 
			this.Name_Label.AllowParentOverrides = false;
			this.Name_Label.AutoEllipsis = false;
			this.Name_Label.Cursor = System.Windows.Forms.Cursors.Default;
			this.Name_Label.CursorType = System.Windows.Forms.Cursors.Default;
			this.Name_Label.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F);
			this.Name_Label.ForeColor = System.Drawing.SystemColors.ButtonFace;
			this.Name_Label.Location = new System.Drawing.Point(75, 51);
			this.Name_Label.Name = "Name_Label";
			this.Name_Label.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Name_Label.Size = new System.Drawing.Size(86, 37);
			this.Name_Label.TabIndex = 22;
			this.Name_Label.Text = "Name";
			this.Name_Label.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
			this.Name_Label.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
			// 
			// SubjectID_comboBox
			// 
			this.SubjectID_comboBox.FormattingEnabled = true;
			this.SubjectID_comboBox.Location = new System.Drawing.Point(582, 121);
			this.SubjectID_comboBox.Name = "SubjectID_comboBox";
			this.SubjectID_comboBox.Size = new System.Drawing.Size(367, 33);
			this.SubjectID_comboBox.TabIndex = 21;
			this.SubjectID_comboBox.SelectedIndexChanged += new System.EventHandler(this.comboBox1_SelectedIndexChanged);
			// 
			// HireDate_DatePicker
			// 
			this.HireDate_DatePicker.BackColor = System.Drawing.Color.Transparent;
			this.HireDate_DatePicker.BorderColor = System.Drawing.Color.Silver;
			this.HireDate_DatePicker.BorderRadius = 1;
			this.HireDate_DatePicker.Color = System.Drawing.Color.Silver;
			this.HireDate_DatePicker.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
			this.HireDate_DatePicker.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
			this.HireDate_DatePicker.DisabledColor = System.Drawing.Color.Gray;
			this.HireDate_DatePicker.DisplayWeekNumbers = false;
			this.HireDate_DatePicker.DPHeight = 0;
			this.HireDate_DatePicker.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
			this.HireDate_DatePicker.FillDatePicker = false;
			this.HireDate_DatePicker.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F);
			this.HireDate_DatePicker.ForeColor = System.Drawing.SystemColors.ButtonFace;
			this.HireDate_DatePicker.Icon = ((System.Drawing.Image)(resources.GetObject("HireDate_DatePicker.Icon")));
			this.HireDate_DatePicker.IconColor = System.Drawing.Color.Gray;
			this.HireDate_DatePicker.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
			this.HireDate_DatePicker.LeftTextMargin = 5;
			this.HireDate_DatePicker.Location = new System.Drawing.Point(582, 272);
			this.HireDate_DatePicker.MinimumSize = new System.Drawing.Size(4, 32);
			this.HireDate_DatePicker.Name = "HireDate_DatePicker";
			this.HireDate_DatePicker.Size = new System.Drawing.Size(367, 44);
			this.HireDate_DatePicker.TabIndex = 19;
			this.HireDate_DatePicker.ValueChanged += new System.EventHandler(this.HireDate_DatePicker_ValueChanged);
			// 
			// Phone_TextBox
			// 
			this.Phone_TextBox.AcceptsReturn = false;
			this.Phone_TextBox.AcceptsTab = false;
			this.Phone_TextBox.AnimationSpeed = 200;
			this.Phone_TextBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
			this.Phone_TextBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
			this.Phone_TextBox.AutoSizeHeight = true;
			this.Phone_TextBox.BackColor = System.Drawing.Color.Transparent;
			this.Phone_TextBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Phone_TextBox.BackgroundImage")));
			this.Phone_TextBox.BorderColorActive = System.Drawing.Color.DodgerBlue;
			this.Phone_TextBox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.Phone_TextBox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			this.Phone_TextBox.BorderColorIdle = System.Drawing.Color.Silver;
			this.Phone_TextBox.BorderRadius = 1;
			this.Phone_TextBox.BorderThickness = 1;
			this.Phone_TextBox.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
			this.Phone_TextBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
			this.Phone_TextBox.Cursor = System.Windows.Forms.Cursors.IBeam;
			this.Phone_TextBox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
			this.Phone_TextBox.DefaultText = "";
			this.Phone_TextBox.FillColor = System.Drawing.Color.White;
			this.Phone_TextBox.HideSelection = true;
			this.Phone_TextBox.IconLeft = null;
			this.Phone_TextBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
			this.Phone_TextBox.IconPadding = 10;
			this.Phone_TextBox.IconRight = null;
			this.Phone_TextBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
			this.Phone_TextBox.Lines = new string[0];
			this.Phone_TextBox.Location = new System.Drawing.Point(75, 272);
			this.Phone_TextBox.MaxLength = 32767;
			this.Phone_TextBox.MinimumSize = new System.Drawing.Size(1, 1);
			this.Phone_TextBox.Modified = false;
			this.Phone_TextBox.Multiline = false;
			this.Phone_TextBox.Name = "Phone_TextBox";
			stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
			stateProperties1.FillColor = System.Drawing.Color.Empty;
			stateProperties1.ForeColor = System.Drawing.Color.Empty;
			stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.Phone_TextBox.OnActiveState = stateProperties1;
			stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
			stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
			stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
			this.Phone_TextBox.OnDisabledState = stateProperties2;
			stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			stateProperties3.FillColor = System.Drawing.Color.Empty;
			stateProperties3.ForeColor = System.Drawing.Color.Empty;
			stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.Phone_TextBox.OnHoverState = stateProperties3;
			stateProperties4.BorderColor = System.Drawing.Color.Silver;
			stateProperties4.FillColor = System.Drawing.Color.White;
			stateProperties4.ForeColor = System.Drawing.Color.Empty;
			stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.Phone_TextBox.OnIdleState = stateProperties4;
			this.Phone_TextBox.Padding = new System.Windows.Forms.Padding(3);
			this.Phone_TextBox.PasswordChar = '\0';
			this.Phone_TextBox.PlaceholderForeColor = System.Drawing.Color.Silver;
			this.Phone_TextBox.PlaceholderText = "Enter text";
			this.Phone_TextBox.ReadOnly = false;
			this.Phone_TextBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this.Phone_TextBox.SelectedText = "";
			this.Phone_TextBox.SelectionLength = 0;
			this.Phone_TextBox.SelectionStart = 0;
			this.Phone_TextBox.ShortcutsEnabled = true;
			this.Phone_TextBox.Size = new System.Drawing.Size(404, 55);
			this.Phone_TextBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
			this.Phone_TextBox.TabIndex = 14;
			this.Phone_TextBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
			this.Phone_TextBox.TextMarginBottom = 0;
			this.Phone_TextBox.TextMarginLeft = 3;
			this.Phone_TextBox.TextMarginTop = 1;
			this.Phone_TextBox.TextPlaceholder = "Enter text";
			this.Phone_TextBox.UseSystemPasswordChar = false;
			this.Phone_TextBox.WordWrap = true;
			this.Phone_TextBox.TextChanged += new System.EventHandler(this.Phone_TextBox_TextChanged);
			// 
			// FullName_TextBox
			// 
			this.FullName_TextBox.AcceptsReturn = false;
			this.FullName_TextBox.AcceptsTab = false;
			this.FullName_TextBox.AnimationSpeed = 200;
			this.FullName_TextBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
			this.FullName_TextBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
			this.FullName_TextBox.AutoSizeHeight = true;
			this.FullName_TextBox.BackColor = System.Drawing.Color.Transparent;
			this.FullName_TextBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("FullName_TextBox.BackgroundImage")));
			this.FullName_TextBox.BorderColorActive = System.Drawing.Color.DodgerBlue;
			this.FullName_TextBox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.FullName_TextBox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			this.FullName_TextBox.BorderColorIdle = System.Drawing.Color.Silver;
			this.FullName_TextBox.BorderRadius = 1;
			this.FullName_TextBox.BorderThickness = 1;
			this.FullName_TextBox.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
			this.FullName_TextBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
			this.FullName_TextBox.Cursor = System.Windows.Forms.Cursors.IBeam;
			this.FullName_TextBox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
			this.FullName_TextBox.DefaultText = "";
			this.FullName_TextBox.FillColor = System.Drawing.Color.White;
			this.FullName_TextBox.HideSelection = true;
			this.FullName_TextBox.IconLeft = null;
			this.FullName_TextBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
			this.FullName_TextBox.IconPadding = 10;
			this.FullName_TextBox.IconRight = null;
			this.FullName_TextBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
			this.FullName_TextBox.Lines = new string[0];
			this.FullName_TextBox.Location = new System.Drawing.Point(75, 115);
			this.FullName_TextBox.MaxLength = 32767;
			this.FullName_TextBox.MinimumSize = new System.Drawing.Size(1, 1);
			this.FullName_TextBox.Modified = false;
			this.FullName_TextBox.Multiline = false;
			this.FullName_TextBox.Name = "FullName_TextBox";
			stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
			stateProperties5.FillColor = System.Drawing.Color.Empty;
			stateProperties5.ForeColor = System.Drawing.Color.Empty;
			stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.FullName_TextBox.OnActiveState = stateProperties5;
			stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
			stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
			stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
			this.FullName_TextBox.OnDisabledState = stateProperties6;
			stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			stateProperties7.FillColor = System.Drawing.Color.Empty;
			stateProperties7.ForeColor = System.Drawing.Color.Empty;
			stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.FullName_TextBox.OnHoverState = stateProperties7;
			stateProperties8.BorderColor = System.Drawing.Color.Silver;
			stateProperties8.FillColor = System.Drawing.Color.White;
			stateProperties8.ForeColor = System.Drawing.Color.Empty;
			stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.FullName_TextBox.OnIdleState = stateProperties8;
			this.FullName_TextBox.Padding = new System.Windows.Forms.Padding(3);
			this.FullName_TextBox.PasswordChar = '\0';
			this.FullName_TextBox.PlaceholderForeColor = System.Drawing.Color.Silver;
			this.FullName_TextBox.PlaceholderText = "Enter text";
			this.FullName_TextBox.ReadOnly = false;
			this.FullName_TextBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this.FullName_TextBox.SelectedText = "";
			this.FullName_TextBox.SelectionLength = 0;
			this.FullName_TextBox.SelectionStart = 0;
			this.FullName_TextBox.ShortcutsEnabled = true;
			this.FullName_TextBox.Size = new System.Drawing.Size(404, 55);
			this.FullName_TextBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
			this.FullName_TextBox.TabIndex = 13;
			this.FullName_TextBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
			this.FullName_TextBox.TextMarginBottom = 0;
			this.FullName_TextBox.TextMarginLeft = 3;
			this.FullName_TextBox.TextMarginTop = 1;
			this.FullName_TextBox.TextPlaceholder = "Enter text";
			this.FullName_TextBox.UseSystemPasswordChar = false;
			this.FullName_TextBox.WordWrap = true;
			this.FullName_TextBox.TextChanged += new System.EventHandler(this.FullName_TextBox_TextChanged);
			// 
			// Back_Button_2
			// 
			this.Back_Button_2.AllowAnimations = true;
			this.Back_Button_2.AllowMouseEffects = true;
			this.Back_Button_2.AllowToggling = false;
			this.Back_Button_2.AnimationSpeed = 200;
			this.Back_Button_2.AutoGenerateColors = false;
			this.Back_Button_2.AutoRoundBorders = false;
			this.Back_Button_2.AutoSizeLeftIcon = true;
			this.Back_Button_2.AutoSizeRightIcon = true;
			this.Back_Button_2.BackColor = System.Drawing.Color.Transparent;
			this.Back_Button_2.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
			this.Back_Button_2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Back_Button_2.BackgroundImage")));
			this.Back_Button_2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.Back_Button_2.ButtonText = "Back";
			this.Back_Button_2.ButtonTextMarginLeft = 0;
			this.Back_Button_2.ColorContrastOnClick = 45;
			this.Back_Button_2.ColorContrastOnHover = 45;
			this.Back_Button_2.Cursor = System.Windows.Forms.Cursors.Default;
			borderEdges4.BottomLeft = true;
			borderEdges4.BottomRight = true;
			borderEdges4.TopLeft = true;
			borderEdges4.TopRight = true;
			this.Back_Button_2.CustomizableEdges = borderEdges4;
			this.Back_Button_2.DialogResult = System.Windows.Forms.DialogResult.None;
			this.Back_Button_2.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
			this.Back_Button_2.DisabledFillColor = System.Drawing.Color.Empty;
			this.Back_Button_2.DisabledForecolor = System.Drawing.Color.Empty;
			this.Back_Button_2.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
			this.Back_Button_2.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.Back_Button_2.ForeColor = System.Drawing.Color.White;
			this.Back_Button_2.IconLeft = null;
			this.Back_Button_2.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.Back_Button_2.IconLeftCursor = System.Windows.Forms.Cursors.Default;
			this.Back_Button_2.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
			this.Back_Button_2.IconMarginLeft = 11;
			this.Back_Button_2.IconPadding = 10;
			this.Back_Button_2.IconRight = null;
			this.Back_Button_2.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
			this.Back_Button_2.IconRightCursor = System.Windows.Forms.Cursors.Default;
			this.Back_Button_2.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
			this.Back_Button_2.IconSize = 25;
			this.Back_Button_2.IdleBorderColor = System.Drawing.Color.Empty;
			this.Back_Button_2.IdleBorderRadius = 0;
			this.Back_Button_2.IdleBorderThickness = 0;
			this.Back_Button_2.IdleFillColor = System.Drawing.Color.Empty;
			this.Back_Button_2.IdleIconLeftImage = null;
			this.Back_Button_2.IdleIconRightImage = null;
			this.Back_Button_2.IndicateFocus = false;
			this.Back_Button_2.Location = new System.Drawing.Point(99, 553);
			this.Back_Button_2.Margin = new System.Windows.Forms.Padding(6);
			this.Back_Button_2.Name = "Back_Button_2";
			this.Back_Button_2.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
			this.Back_Button_2.OnDisabledState.BorderRadius = 1;
			this.Back_Button_2.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.Back_Button_2.OnDisabledState.BorderThickness = 1;
			this.Back_Button_2.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.Back_Button_2.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
			this.Back_Button_2.OnDisabledState.IconLeftImage = null;
			this.Back_Button_2.OnDisabledState.IconRightImage = null;
			this.Back_Button_2.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
			this.Back_Button_2.onHoverState.BorderRadius = 1;
			this.Back_Button_2.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.Back_Button_2.onHoverState.BorderThickness = 1;
			this.Back_Button_2.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
			this.Back_Button_2.onHoverState.ForeColor = System.Drawing.Color.White;
			this.Back_Button_2.onHoverState.IconLeftImage = null;
			this.Back_Button_2.onHoverState.IconRightImage = null;
			this.Back_Button_2.OnIdleState.BorderColor = System.Drawing.Color.Silver;
			this.Back_Button_2.OnIdleState.BorderRadius = 1;
			this.Back_Button_2.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.Back_Button_2.OnIdleState.BorderThickness = 1;
			this.Back_Button_2.OnIdleState.FillColor = System.Drawing.Color.DimGray;
			this.Back_Button_2.OnIdleState.ForeColor = System.Drawing.Color.White;
			this.Back_Button_2.OnIdleState.IconLeftImage = null;
			this.Back_Button_2.OnIdleState.IconRightImage = null;
			this.Back_Button_2.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(71)))));
			this.Back_Button_2.OnPressedState.BorderRadius = 1;
			this.Back_Button_2.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.Back_Button_2.OnPressedState.BorderThickness = 1;
			this.Back_Button_2.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(71)))));
			this.Back_Button_2.OnPressedState.ForeColor = System.Drawing.Color.White;
			this.Back_Button_2.OnPressedState.IconLeftImage = null;
			this.Back_Button_2.OnPressedState.IconRightImage = null;
			this.Back_Button_2.Size = new System.Drawing.Size(196, 62);
			this.Back_Button_2.TabIndex = 17;
			this.Back_Button_2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			this.Back_Button_2.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
			this.Back_Button_2.TextMarginLeft = 0;
			this.Back_Button_2.TextPadding = new System.Windows.Forms.Padding(0);
			this.Back_Button_2.UseDefaultRadiusAndThickness = true;
			this.Back_Button_2.Click += new System.EventHandler(this.save_Click);
			// 
			// Insert_Button
			// 
			this.Insert_Button.AllowAnimations = true;
			this.Insert_Button.AllowMouseEffects = true;
			this.Insert_Button.AllowToggling = false;
			this.Insert_Button.AnimationSpeed = 200;
			this.Insert_Button.AutoGenerateColors = false;
			this.Insert_Button.AutoRoundBorders = false;
			this.Insert_Button.AutoSizeLeftIcon = true;
			this.Insert_Button.AutoSizeRightIcon = true;
			this.Insert_Button.BackColor = System.Drawing.Color.Transparent;
			this.Insert_Button.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
			this.Insert_Button.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Insert_Button.BackgroundImage")));
			this.Insert_Button.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.Insert_Button.ButtonText = "Insert";
			this.Insert_Button.ButtonTextMarginLeft = 0;
			this.Insert_Button.ColorContrastOnClick = 45;
			this.Insert_Button.ColorContrastOnHover = 45;
			this.Insert_Button.Cursor = System.Windows.Forms.Cursors.Default;
			borderEdges5.BottomLeft = true;
			borderEdges5.BottomRight = true;
			borderEdges5.TopLeft = true;
			borderEdges5.TopRight = true;
			this.Insert_Button.CustomizableEdges = borderEdges5;
			this.Insert_Button.DialogResult = System.Windows.Forms.DialogResult.None;
			this.Insert_Button.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
			this.Insert_Button.DisabledFillColor = System.Drawing.Color.Empty;
			this.Insert_Button.DisabledForecolor = System.Drawing.Color.Empty;
			this.Insert_Button.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
			this.Insert_Button.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.Insert_Button.ForeColor = System.Drawing.Color.White;
			this.Insert_Button.IconLeft = null;
			this.Insert_Button.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.Insert_Button.IconLeftCursor = System.Windows.Forms.Cursors.Default;
			this.Insert_Button.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
			this.Insert_Button.IconMarginLeft = 11;
			this.Insert_Button.IconPadding = 10;
			this.Insert_Button.IconRight = null;
			this.Insert_Button.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
			this.Insert_Button.IconRightCursor = System.Windows.Forms.Cursors.Default;
			this.Insert_Button.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
			this.Insert_Button.IconSize = 25;
			this.Insert_Button.IdleBorderColor = System.Drawing.Color.Empty;
			this.Insert_Button.IdleBorderRadius = 0;
			this.Insert_Button.IdleBorderThickness = 0;
			this.Insert_Button.IdleFillColor = System.Drawing.Color.Empty;
			this.Insert_Button.IdleIconLeftImage = null;
			this.Insert_Button.IdleIconRightImage = null;
			this.Insert_Button.IndicateFocus = false;
			this.Insert_Button.Location = new System.Drawing.Point(99, 553);
			this.Insert_Button.Margin = new System.Windows.Forms.Padding(6);
			this.Insert_Button.Name = "Insert_Button";
			this.Insert_Button.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
			this.Insert_Button.OnDisabledState.BorderRadius = 1;
			this.Insert_Button.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.Insert_Button.OnDisabledState.BorderThickness = 1;
			this.Insert_Button.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.Insert_Button.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
			this.Insert_Button.OnDisabledState.IconLeftImage = null;
			this.Insert_Button.OnDisabledState.IconRightImage = null;
			this.Insert_Button.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
			this.Insert_Button.onHoverState.BorderRadius = 1;
			this.Insert_Button.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.Insert_Button.onHoverState.BorderThickness = 1;
			this.Insert_Button.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
			this.Insert_Button.onHoverState.ForeColor = System.Drawing.Color.White;
			this.Insert_Button.onHoverState.IconLeftImage = null;
			this.Insert_Button.onHoverState.IconRightImage = null;
			this.Insert_Button.OnIdleState.BorderColor = System.Drawing.Color.Silver;
			this.Insert_Button.OnIdleState.BorderRadius = 1;
			this.Insert_Button.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.Insert_Button.OnIdleState.BorderThickness = 1;
			this.Insert_Button.OnIdleState.FillColor = System.Drawing.Color.DimGray;
			this.Insert_Button.OnIdleState.ForeColor = System.Drawing.Color.White;
			this.Insert_Button.OnIdleState.IconLeftImage = null;
			this.Insert_Button.OnIdleState.IconRightImage = null;
			this.Insert_Button.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(71)))));
			this.Insert_Button.OnPressedState.BorderRadius = 1;
			this.Insert_Button.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.Insert_Button.OnPressedState.BorderThickness = 1;
			this.Insert_Button.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(71)))));
			this.Insert_Button.OnPressedState.ForeColor = System.Drawing.Color.White;
			this.Insert_Button.OnPressedState.IconLeftImage = null;
			this.Insert_Button.OnPressedState.IconRightImage = null;
			this.Insert_Button.Size = new System.Drawing.Size(196, 62);
			this.Insert_Button.TabIndex = 18;
			this.Insert_Button.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			this.Insert_Button.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
			this.Insert_Button.TextMarginLeft = 0;
			this.Insert_Button.TextPadding = new System.Windows.Forms.Padding(0);
			this.Insert_Button.UseDefaultRadiusAndThickness = true;
			this.Insert_Button.Click += new System.EventHandler(this.bunifuButton1_Click);
			// 
			// Assign_Button
			// 
			this.Assign_Button.AllowAnimations = true;
			this.Assign_Button.AllowMouseEffects = true;
			this.Assign_Button.AllowToggling = false;
			this.Assign_Button.AnimationSpeed = 200;
			this.Assign_Button.AutoGenerateColors = false;
			this.Assign_Button.AutoRoundBorders = false;
			this.Assign_Button.AutoSizeLeftIcon = true;
			this.Assign_Button.AutoSizeRightIcon = true;
			this.Assign_Button.BackColor = System.Drawing.Color.Transparent;
			this.Assign_Button.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
			this.Assign_Button.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Assign_Button.BackgroundImage")));
			this.Assign_Button.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.Assign_Button.ButtonText = "Assign";
			this.Assign_Button.ButtonTextMarginLeft = 0;
			this.Assign_Button.ColorContrastOnClick = 45;
			this.Assign_Button.ColorContrastOnHover = 45;
			this.Assign_Button.Cursor = System.Windows.Forms.Cursors.Default;
			borderEdges6.BottomLeft = true;
			borderEdges6.BottomRight = true;
			borderEdges6.TopLeft = true;
			borderEdges6.TopRight = true;
			this.Assign_Button.CustomizableEdges = borderEdges6;
			this.Assign_Button.DialogResult = System.Windows.Forms.DialogResult.None;
			this.Assign_Button.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
			this.Assign_Button.DisabledFillColor = System.Drawing.Color.Empty;
			this.Assign_Button.DisabledForecolor = System.Drawing.Color.Empty;
			this.Assign_Button.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
			this.Assign_Button.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.Assign_Button.ForeColor = System.Drawing.Color.White;
			this.Assign_Button.IconLeft = null;
			this.Assign_Button.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.Assign_Button.IconLeftCursor = System.Windows.Forms.Cursors.Default;
			this.Assign_Button.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
			this.Assign_Button.IconMarginLeft = 11;
			this.Assign_Button.IconPadding = 10;
			this.Assign_Button.IconRight = null;
			this.Assign_Button.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
			this.Assign_Button.IconRightCursor = System.Windows.Forms.Cursors.Default;
			this.Assign_Button.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
			this.Assign_Button.IconSize = 25;
			this.Assign_Button.IdleBorderColor = System.Drawing.Color.Empty;
			this.Assign_Button.IdleBorderRadius = 0;
			this.Assign_Button.IdleBorderThickness = 0;
			this.Assign_Button.IdleFillColor = System.Drawing.Color.Empty;
			this.Assign_Button.IdleIconLeftImage = null;
			this.Assign_Button.IdleIconRightImage = null;
			this.Assign_Button.IndicateFocus = false;
			this.Assign_Button.Location = new System.Drawing.Point(537, 553);
			this.Assign_Button.Margin = new System.Windows.Forms.Padding(6);
			this.Assign_Button.Name = "Assign_Button";
			this.Assign_Button.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
			this.Assign_Button.OnDisabledState.BorderRadius = 1;
			this.Assign_Button.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.Assign_Button.OnDisabledState.BorderThickness = 1;
			this.Assign_Button.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.Assign_Button.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
			this.Assign_Button.OnDisabledState.IconLeftImage = null;
			this.Assign_Button.OnDisabledState.IconRightImage = null;
			this.Assign_Button.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
			this.Assign_Button.onHoverState.BorderRadius = 1;
			this.Assign_Button.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.Assign_Button.onHoverState.BorderThickness = 1;
			this.Assign_Button.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
			this.Assign_Button.onHoverState.ForeColor = System.Drawing.Color.White;
			this.Assign_Button.onHoverState.IconLeftImage = null;
			this.Assign_Button.onHoverState.IconRightImage = null;
			this.Assign_Button.OnIdleState.BorderColor = System.Drawing.Color.Silver;
			this.Assign_Button.OnIdleState.BorderRadius = 1;
			this.Assign_Button.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.Assign_Button.OnIdleState.BorderThickness = 1;
			this.Assign_Button.OnIdleState.FillColor = System.Drawing.Color.DimGray;
			this.Assign_Button.OnIdleState.ForeColor = System.Drawing.Color.White;
			this.Assign_Button.OnIdleState.IconLeftImage = null;
			this.Assign_Button.OnIdleState.IconRightImage = null;
			this.Assign_Button.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(71)))));
			this.Assign_Button.OnPressedState.BorderRadius = 1;
			this.Assign_Button.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.Assign_Button.OnPressedState.BorderThickness = 1;
			this.Assign_Button.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(71)))));
			this.Assign_Button.OnPressedState.ForeColor = System.Drawing.Color.White;
			this.Assign_Button.OnPressedState.IconLeftImage = null;
			this.Assign_Button.OnPressedState.IconRightImage = null;
			this.Assign_Button.Size = new System.Drawing.Size(196, 62);
			this.Assign_Button.TabIndex = 19;
			this.Assign_Button.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			this.Assign_Button.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
			this.Assign_Button.TextMarginLeft = 0;
			this.Assign_Button.TextPadding = new System.Windows.Forms.Padding(0);
			this.Assign_Button.UseDefaultRadiusAndThickness = true;
			this.Assign_Button.Click += new System.EventHandler(this.bunifuButton1_Click_1);
			// 
			// Assign_Class_Button
			// 
			this.Assign_Class_Button.AllowAnimations = true;
			this.Assign_Class_Button.AllowMouseEffects = true;
			this.Assign_Class_Button.AllowToggling = false;
			this.Assign_Class_Button.AnimationSpeed = 200;
			this.Assign_Class_Button.AutoGenerateColors = false;
			this.Assign_Class_Button.AutoRoundBorders = false;
			this.Assign_Class_Button.AutoSizeLeftIcon = true;
			this.Assign_Class_Button.AutoSizeRightIcon = true;
			this.Assign_Class_Button.BackColor = System.Drawing.Color.Transparent;
			this.Assign_Class_Button.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
			this.Assign_Class_Button.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Assign_Class_Button.BackgroundImage")));
			this.Assign_Class_Button.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.Assign_Class_Button.ButtonText = "Assign Class";
			this.Assign_Class_Button.ButtonTextMarginLeft = 0;
			this.Assign_Class_Button.ColorContrastOnClick = 45;
			this.Assign_Class_Button.ColorContrastOnHover = 45;
			this.Assign_Class_Button.Cursor = System.Windows.Forms.Cursors.Default;
			borderEdges7.BottomLeft = true;
			borderEdges7.BottomRight = true;
			borderEdges7.TopLeft = true;
			borderEdges7.TopRight = true;
			this.Assign_Class_Button.CustomizableEdges = borderEdges7;
			this.Assign_Class_Button.DialogResult = System.Windows.Forms.DialogResult.None;
			this.Assign_Class_Button.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
			this.Assign_Class_Button.DisabledFillColor = System.Drawing.Color.Empty;
			this.Assign_Class_Button.DisabledForecolor = System.Drawing.Color.Empty;
			this.Assign_Class_Button.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
			this.Assign_Class_Button.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.Assign_Class_Button.ForeColor = System.Drawing.Color.White;
			this.Assign_Class_Button.IconLeft = null;
			this.Assign_Class_Button.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.Assign_Class_Button.IconLeftCursor = System.Windows.Forms.Cursors.Default;
			this.Assign_Class_Button.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
			this.Assign_Class_Button.IconMarginLeft = 11;
			this.Assign_Class_Button.IconPadding = 10;
			this.Assign_Class_Button.IconRight = null;
			this.Assign_Class_Button.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
			this.Assign_Class_Button.IconRightCursor = System.Windows.Forms.Cursors.Default;
			this.Assign_Class_Button.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
			this.Assign_Class_Button.IconSize = 25;
			this.Assign_Class_Button.IdleBorderColor = System.Drawing.Color.Empty;
			this.Assign_Class_Button.IdleBorderRadius = 0;
			this.Assign_Class_Button.IdleBorderThickness = 0;
			this.Assign_Class_Button.IdleFillColor = System.Drawing.Color.Empty;
			this.Assign_Class_Button.IdleIconLeftImage = null;
			this.Assign_Class_Button.IdleIconRightImage = null;
			this.Assign_Class_Button.IndicateFocus = false;
			this.Assign_Class_Button.Location = new System.Drawing.Point(774, 553);
			this.Assign_Class_Button.Margin = new System.Windows.Forms.Padding(6);
			this.Assign_Class_Button.Name = "Assign_Class_Button";
			this.Assign_Class_Button.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
			this.Assign_Class_Button.OnDisabledState.BorderRadius = 1;
			this.Assign_Class_Button.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.Assign_Class_Button.OnDisabledState.BorderThickness = 1;
			this.Assign_Class_Button.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.Assign_Class_Button.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
			this.Assign_Class_Button.OnDisabledState.IconLeftImage = null;
			this.Assign_Class_Button.OnDisabledState.IconRightImage = null;
			this.Assign_Class_Button.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
			this.Assign_Class_Button.onHoverState.BorderRadius = 1;
			this.Assign_Class_Button.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.Assign_Class_Button.onHoverState.BorderThickness = 1;
			this.Assign_Class_Button.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
			this.Assign_Class_Button.onHoverState.ForeColor = System.Drawing.Color.White;
			this.Assign_Class_Button.onHoverState.IconLeftImage = null;
			this.Assign_Class_Button.onHoverState.IconRightImage = null;
			this.Assign_Class_Button.OnIdleState.BorderColor = System.Drawing.Color.Silver;
			this.Assign_Class_Button.OnIdleState.BorderRadius = 1;
			this.Assign_Class_Button.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.Assign_Class_Button.OnIdleState.BorderThickness = 1;
			this.Assign_Class_Button.OnIdleState.FillColor = System.Drawing.Color.DimGray;
			this.Assign_Class_Button.OnIdleState.ForeColor = System.Drawing.Color.White;
			this.Assign_Class_Button.OnIdleState.IconLeftImage = null;
			this.Assign_Class_Button.OnIdleState.IconRightImage = null;
			this.Assign_Class_Button.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(71)))));
			this.Assign_Class_Button.OnPressedState.BorderRadius = 1;
			this.Assign_Class_Button.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.Assign_Class_Button.OnPressedState.BorderThickness = 1;
			this.Assign_Class_Button.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(71)))));
			this.Assign_Class_Button.OnPressedState.ForeColor = System.Drawing.Color.White;
			this.Assign_Class_Button.OnPressedState.IconLeftImage = null;
			this.Assign_Class_Button.OnPressedState.IconRightImage = null;
			this.Assign_Class_Button.Size = new System.Drawing.Size(196, 62);
			this.Assign_Class_Button.TabIndex = 20;
			this.Assign_Class_Button.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			this.Assign_Class_Button.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
			this.Assign_Class_Button.TextMarginLeft = 0;
			this.Assign_Class_Button.TextPadding = new System.Windows.Forms.Padding(0);
			this.Assign_Class_Button.UseDefaultRadiusAndThickness = true;
			this.Assign_Class_Button.Click += new System.EventHandler(this.bunifuButton1_Click_2);
			// 
			// Delet_Button
			// 
			this.Delet_Button.AllowAnimations = true;
			this.Delet_Button.AllowMouseEffects = true;
			this.Delet_Button.AllowToggling = false;
			this.Delet_Button.AnimationSpeed = 200;
			this.Delet_Button.AutoGenerateColors = false;
			this.Delet_Button.AutoRoundBorders = false;
			this.Delet_Button.AutoSizeLeftIcon = true;
			this.Delet_Button.AutoSizeRightIcon = true;
			this.Delet_Button.BackColor = System.Drawing.Color.Transparent;
			this.Delet_Button.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
			this.Delet_Button.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Delet_Button.BackgroundImage")));
			this.Delet_Button.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.Delet_Button.ButtonText = "Delete";
			this.Delet_Button.ButtonTextMarginLeft = 0;
			this.Delet_Button.ColorContrastOnClick = 45;
			this.Delet_Button.ColorContrastOnHover = 45;
			this.Delet_Button.Cursor = System.Windows.Forms.Cursors.Default;
			borderEdges8.BottomLeft = true;
			borderEdges8.BottomRight = true;
			borderEdges8.TopLeft = true;
			borderEdges8.TopRight = true;
			this.Delet_Button.CustomizableEdges = borderEdges8;
			this.Delet_Button.DialogResult = System.Windows.Forms.DialogResult.None;
			this.Delet_Button.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
			this.Delet_Button.DisabledFillColor = System.Drawing.Color.Empty;
			this.Delet_Button.DisabledForecolor = System.Drawing.Color.Empty;
			this.Delet_Button.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
			this.Delet_Button.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.Delet_Button.ForeColor = System.Drawing.Color.White;
			this.Delet_Button.IconLeft = null;
			this.Delet_Button.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.Delet_Button.IconLeftCursor = System.Windows.Forms.Cursors.Default;
			this.Delet_Button.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
			this.Delet_Button.IconMarginLeft = 11;
			this.Delet_Button.IconPadding = 10;
			this.Delet_Button.IconRight = null;
			this.Delet_Button.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
			this.Delet_Button.IconRightCursor = System.Windows.Forms.Cursors.Default;
			this.Delet_Button.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
			this.Delet_Button.IconSize = 25;
			this.Delet_Button.IdleBorderColor = System.Drawing.Color.Empty;
			this.Delet_Button.IdleBorderRadius = 0;
			this.Delet_Button.IdleBorderThickness = 0;
			this.Delet_Button.IdleFillColor = System.Drawing.Color.Empty;
			this.Delet_Button.IdleIconLeftImage = null;
			this.Delet_Button.IdleIconRightImage = null;
			this.Delet_Button.IndicateFocus = false;
			this.Delet_Button.Location = new System.Drawing.Point(997, 232);
			this.Delet_Button.Margin = new System.Windows.Forms.Padding(6);
			this.Delet_Button.Name = "Delet_Button";
			this.Delet_Button.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
			this.Delet_Button.OnDisabledState.BorderRadius = 1;
			this.Delet_Button.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.Delet_Button.OnDisabledState.BorderThickness = 1;
			this.Delet_Button.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.Delet_Button.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
			this.Delet_Button.OnDisabledState.IconLeftImage = null;
			this.Delet_Button.OnDisabledState.IconRightImage = null;
			this.Delet_Button.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
			this.Delet_Button.onHoverState.BorderRadius = 1;
			this.Delet_Button.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.Delet_Button.onHoverState.BorderThickness = 1;
			this.Delet_Button.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
			this.Delet_Button.onHoverState.ForeColor = System.Drawing.Color.White;
			this.Delet_Button.onHoverState.IconLeftImage = null;
			this.Delet_Button.onHoverState.IconRightImage = null;
			this.Delet_Button.OnIdleState.BorderColor = System.Drawing.Color.Silver;
			this.Delet_Button.OnIdleState.BorderRadius = 1;
			this.Delet_Button.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.Delet_Button.OnIdleState.BorderThickness = 1;
			this.Delet_Button.OnIdleState.FillColor = System.Drawing.Color.DimGray;
			this.Delet_Button.OnIdleState.ForeColor = System.Drawing.Color.White;
			this.Delet_Button.OnIdleState.IconLeftImage = null;
			this.Delet_Button.OnIdleState.IconRightImage = null;
			this.Delet_Button.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(71)))));
			this.Delet_Button.OnPressedState.BorderRadius = 1;
			this.Delet_Button.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.Delet_Button.OnPressedState.BorderThickness = 1;
			this.Delet_Button.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(71)))));
			this.Delet_Button.OnPressedState.ForeColor = System.Drawing.Color.White;
			this.Delet_Button.OnPressedState.IconLeftImage = null;
			this.Delet_Button.OnPressedState.IconRightImage = null;
			this.Delet_Button.Size = new System.Drawing.Size(196, 62);
			this.Delet_Button.TabIndex = 21;
			this.Delet_Button.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			this.Delet_Button.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
			this.Delet_Button.TextMarginLeft = 0;
			this.Delet_Button.TextPadding = new System.Windows.Forms.Padding(0);
			this.Delet_Button.UseDefaultRadiusAndThickness = true;
			this.Delet_Button.Click += new System.EventHandler(this.bunifuButton1_Click_3);
			// 
			// Edit_Button
			// 
			this.Edit_Button.AllowAnimations = true;
			this.Edit_Button.AllowMouseEffects = true;
			this.Edit_Button.AllowToggling = false;
			this.Edit_Button.AnimationSpeed = 200;
			this.Edit_Button.AutoGenerateColors = false;
			this.Edit_Button.AutoRoundBorders = false;
			this.Edit_Button.AutoSizeLeftIcon = true;
			this.Edit_Button.AutoSizeRightIcon = true;
			this.Edit_Button.BackColor = System.Drawing.Color.Transparent;
			this.Edit_Button.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
			this.Edit_Button.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Edit_Button.BackgroundImage")));
			this.Edit_Button.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.Edit_Button.ButtonText = "Edit";
			this.Edit_Button.ButtonTextMarginLeft = 0;
			this.Edit_Button.ColorContrastOnClick = 45;
			this.Edit_Button.ColorContrastOnHover = 45;
			this.Edit_Button.Cursor = System.Windows.Forms.Cursors.Default;
			borderEdges9.BottomLeft = true;
			borderEdges9.BottomRight = true;
			borderEdges9.TopLeft = true;
			borderEdges9.TopRight = true;
			this.Edit_Button.CustomizableEdges = borderEdges9;
			this.Edit_Button.DialogResult = System.Windows.Forms.DialogResult.None;
			this.Edit_Button.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
			this.Edit_Button.DisabledFillColor = System.Drawing.Color.Empty;
			this.Edit_Button.DisabledForecolor = System.Drawing.Color.Empty;
			this.Edit_Button.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
			this.Edit_Button.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.Edit_Button.ForeColor = System.Drawing.Color.White;
			this.Edit_Button.IconLeft = null;
			this.Edit_Button.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.Edit_Button.IconLeftCursor = System.Windows.Forms.Cursors.Default;
			this.Edit_Button.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
			this.Edit_Button.IconMarginLeft = 11;
			this.Edit_Button.IconPadding = 10;
			this.Edit_Button.IconRight = null;
			this.Edit_Button.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
			this.Edit_Button.IconRightCursor = System.Windows.Forms.Cursors.Default;
			this.Edit_Button.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
			this.Edit_Button.IconSize = 25;
			this.Edit_Button.IdleBorderColor = System.Drawing.Color.Empty;
			this.Edit_Button.IdleBorderRadius = 0;
			this.Edit_Button.IdleBorderThickness = 0;
			this.Edit_Button.IdleFillColor = System.Drawing.Color.Empty;
			this.Edit_Button.IdleIconLeftImage = null;
			this.Edit_Button.IdleIconRightImage = null;
			this.Edit_Button.IndicateFocus = false;
			this.Edit_Button.Location = new System.Drawing.Point(997, 358);
			this.Edit_Button.Margin = new System.Windows.Forms.Padding(6);
			this.Edit_Button.Name = "Edit_Button";
			this.Edit_Button.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
			this.Edit_Button.OnDisabledState.BorderRadius = 1;
			this.Edit_Button.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.Edit_Button.OnDisabledState.BorderThickness = 1;
			this.Edit_Button.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.Edit_Button.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
			this.Edit_Button.OnDisabledState.IconLeftImage = null;
			this.Edit_Button.OnDisabledState.IconRightImage = null;
			this.Edit_Button.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
			this.Edit_Button.onHoverState.BorderRadius = 1;
			this.Edit_Button.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.Edit_Button.onHoverState.BorderThickness = 1;
			this.Edit_Button.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
			this.Edit_Button.onHoverState.ForeColor = System.Drawing.Color.White;
			this.Edit_Button.onHoverState.IconLeftImage = null;
			this.Edit_Button.onHoverState.IconRightImage = null;
			this.Edit_Button.OnIdleState.BorderColor = System.Drawing.Color.Silver;
			this.Edit_Button.OnIdleState.BorderRadius = 1;
			this.Edit_Button.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.Edit_Button.OnIdleState.BorderThickness = 1;
			this.Edit_Button.OnIdleState.FillColor = System.Drawing.Color.DimGray;
			this.Edit_Button.OnIdleState.ForeColor = System.Drawing.Color.White;
			this.Edit_Button.OnIdleState.IconLeftImage = null;
			this.Edit_Button.OnIdleState.IconRightImage = null;
			this.Edit_Button.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(71)))));
			this.Edit_Button.OnPressedState.BorderRadius = 1;
			this.Edit_Button.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.Edit_Button.OnPressedState.BorderThickness = 1;
			this.Edit_Button.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(71)))));
			this.Edit_Button.OnPressedState.ForeColor = System.Drawing.Color.White;
			this.Edit_Button.OnPressedState.IconLeftImage = null;
			this.Edit_Button.OnPressedState.IconRightImage = null;
			this.Edit_Button.Size = new System.Drawing.Size(196, 62);
			this.Edit_Button.TabIndex = 22;
			this.Edit_Button.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			this.Edit_Button.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
			this.Edit_Button.TextMarginLeft = 0;
			this.Edit_Button.TextPadding = new System.Windows.Forms.Padding(0);
			this.Edit_Button.UseDefaultRadiusAndThickness = true;
			this.Edit_Button.Click += new System.EventHandler(this.bunifuButton1_Click_4);
			// 
			// message
			// 
			this.message.AllowDragging = false;
			this.message.AllowMultipleViews = true;
			this.message.ClickToClose = true;
			this.message.DoubleClickToClose = true;
			this.message.DurationAfterIdle = 3000;
			this.message.ErrorOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			this.message.ErrorOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			this.message.ErrorOptions.ActionBorderRadius = 1;
			this.message.ErrorOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
			this.message.ErrorOptions.ActionForeColor = System.Drawing.Color.Black;
			this.message.ErrorOptions.BackColor = System.Drawing.Color.White;
			this.message.ErrorOptions.BorderColor = System.Drawing.Color.White;
			this.message.ErrorOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(204)))), ((int)(((byte)(199)))));
			this.message.ErrorOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
			this.message.ErrorOptions.ForeColor = System.Drawing.Color.Black;
			this.message.ErrorOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon")));
			this.message.ErrorOptions.IconLeftMargin = 12;
			this.message.FadeCloseIcon = false;
			this.message.Host = Bunifu.UI.WinForms.BunifuSnackbar.Hosts.FormOwner;
			this.message.InformationOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			this.message.InformationOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			this.message.InformationOptions.ActionBorderRadius = 1;
			this.message.InformationOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
			this.message.InformationOptions.ActionForeColor = System.Drawing.Color.Black;
			this.message.InformationOptions.BackColor = System.Drawing.Color.White;
			this.message.InformationOptions.BorderColor = System.Drawing.Color.White;
			this.message.InformationOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(213)))), ((int)(((byte)(255)))));
			this.message.InformationOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
			this.message.InformationOptions.ForeColor = System.Drawing.Color.Black;
			this.message.InformationOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon1")));
			this.message.InformationOptions.IconLeftMargin = 12;
			this.message.Margin = 10;
			this.message.MaximumSize = new System.Drawing.Size(0, 0);
			this.message.MaximumViews = 7;
			this.message.MessageRightMargin = 15;
			this.message.MessageTopMargin = 0;
			this.message.MinimumSize = new System.Drawing.Size(0, 0);
			this.message.ShowBorders = false;
			this.message.ShowCloseIcon = false;
			this.message.ShowIcon = true;
			this.message.ShowShadows = true;
			this.message.SuccessOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			this.message.SuccessOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			this.message.SuccessOptions.ActionBorderRadius = 1;
			this.message.SuccessOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
			this.message.SuccessOptions.ActionForeColor = System.Drawing.Color.Black;
			this.message.SuccessOptions.BackColor = System.Drawing.Color.White;
			this.message.SuccessOptions.BorderColor = System.Drawing.Color.White;
			this.message.SuccessOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(255)))), ((int)(((byte)(237)))));
			this.message.SuccessOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
			this.message.SuccessOptions.ForeColor = System.Drawing.Color.Black;
			this.message.SuccessOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon2")));
			this.message.SuccessOptions.IconLeftMargin = 12;
			this.message.ViewsMargin = 7;
			this.message.WarningOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			this.message.WarningOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			this.message.WarningOptions.ActionBorderRadius = 1;
			this.message.WarningOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
			this.message.WarningOptions.ActionForeColor = System.Drawing.Color.Black;
			this.message.WarningOptions.BackColor = System.Drawing.Color.White;
			this.message.WarningOptions.BorderColor = System.Drawing.Color.White;
			this.message.WarningOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(229)))), ((int)(((byte)(143)))));
			this.message.WarningOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
			this.message.WarningOptions.ForeColor = System.Drawing.Color.Black;
			this.message.WarningOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon3")));
			this.message.WarningOptions.IconLeftMargin = 12;
			this.message.ZoomCloseIcon = true;
			// 
			// Teacher
			// 
			this.AutoScaleDimensions = new System.Drawing.SizeF(12F, 25F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(76)))));
			this.ClientSize = new System.Drawing.Size(1622, 1082);
			this.Controls.Add(this.Edit_Button);
			this.Controls.Add(this.Delet_Button);
			this.Controls.Add(this.Assign_Class_Button);
			this.Controls.Add(this.Assign_Button);
			this.Controls.Add(this.Insert_Button);
			this.Controls.Add(this.Back_Button_2);
			this.Controls.Add(this.bunifuPanel1);
			this.Controls.Add(this.TeacherRecordsTable);
			this.Name = "Teacher";
			this.Text = "Teacher";
			this.Load += new System.EventHandler(this.Teacher_Load);
			((System.ComponentModel.ISupportInitialize)(this.TeacherRecordsTable)).EndInit();
			this.bunifuPanel1.ResumeLayout(false);
			this.bunifuPanel1.PerformLayout();
			this.ResumeLayout(false);

		}

		#endregion
        private Bunifu.Charts.WinForms.ChartTypes.BunifuBarChart bunifuBarChart1;
        private Bunifu.UI.WinForms.BunifuDataGridView TeacherRecordsTable;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuTextBox Phone_TextBox;
        private Bunifu.UI.WinForms.BunifuTextBox FullName_TextBox;
        private Bunifu.UI.WinForms.BunifuDatePicker HireDate_DatePicker;
        private Bunifu.UI.WinForms.BunifuLabel HireDate_Label;
        private Bunifu.UI.WinForms.BunifuLabel Phone_Label;
        private Bunifu.UI.WinForms.BunifuLabel SubjectID_Label;
        private Bunifu.UI.WinForms.BunifuLabel Name_Label;
        private System.Windows.Forms.ComboBox SubjectID_comboBox;
		private Bunifu.UI.WinForms.BunifuButton.BunifuButton Back_Button_2;
		private Bunifu.UI.WinForms.BunifuButton.BunifuButton Insert_Button;
		private Bunifu.UI.WinForms.BunifuButton.BunifuButton Assign_Button;
		private Bunifu.UI.WinForms.BunifuButton.BunifuButton Assign_Class_Button;
		private Bunifu.UI.WinForms.BunifuButton.BunifuButton Delet_Button;
		private Bunifu.UI.WinForms.BunifuButton.BunifuButton Edit_Button;
		private Bunifu.UI.WinForms.BunifuButton.BunifuButton GoBack_Button;
		private Bunifu.UI.WinForms.BunifuButton.BunifuButton Add_Teacher;
		private Bunifu.UI.WinForms.BunifuButton.BunifuButton EditApplier_Button;
		private Bunifu.UI.WinForms.BunifuSnackbar message;
	}
}